const STYLES = {
    container: {
        position: 'absolute',  // Stay inside the parent container (Arena or Obsidian pane)
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        background: '#000000',
        color: '#ffffff',
        fontFamily: '"Outfit", "Inter", sans-serif',
        overflow: 'hidden',
        boxSizing: 'border-box',
        zIndex: 1,
    },
    glassCard: {
        background: 'rgba(0, 0, 0, 0)',
        borderRadius: '24px',
        padding: 'clamp(12px, 3vh, 32px) clamp(16px, 4vw, 48px)',
        maxWidth: '100%',
        width: 'min(640px, 95vw)',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: 'clamp(10px, 2.5vh, 24px)',
    },
    title: {
        fontSize: 'clamp(36px, 8vmin, 80px)', // Boosted title
        fontWeight: '900',
        color: '#ffffff',
        marginBottom: '6px',
        letterSpacing: '0.2em',
        textTransform: 'uppercase',
        textAlign: 'center'
    },
    subtitle: {
        fontSize: 'clamp(12px, 2.5vmin, 18px)', // Boosted subtitle
        color: 'rgba(255, 255, 255, 0.35)',
        marginBottom: 0,
        letterSpacing: '0.25em',
        fontWeight: '400',
        textAlign: 'center'
    },
    grid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        gap: 'clamp(6px, 1.5vmin, 12px)', // Tighter gap for better vertical fit
        marginBottom: 'clamp(12px, 2vh, 20px)',
        padding: 'clamp(8px, 2vmin, 20px)', // Reduced padding
        background: 'rgba(0, 0, 0, 0.3)',
        borderRadius: '16px',
        border: '1px solid rgba(255, 255, 255, 0.05)',
    },
    cell: {
        width: 'clamp(64px, 14vmin, 160px)', // Larger grid cells
        height: 'clamp(64px, 14vmin, 160px)',
        borderRadius: '8px',
        background: 'rgba(255, 255, 255, 0.08)',
        border: '1px solid rgba(255, 255, 255, 0.2)',
        transition: 'all 0.1s ease-out',
    },
    cellActive: {
        background: '#ffffff',
        border: '1px solid #ffffff',
        boxShadow: '0 0 20px rgba(255, 255, 255, 0.4)',
    },
    controls: {
        display: 'flex',
        flexWrap: 'wrap',
        justifyContent: 'center',
        gap: '16px',
        marginTop: 'clamp(10px, 2vh, 20px)', // Reduced margin
        position: 'relative',
        zIndex: 50,
        pointerEvents: 'auto',
    },
    button: {
        padding: 'clamp(14px, 2.2vh, 20px) clamp(28px, 5vw, 56px)',
        fontSize: 'clamp(14px, 2vmin, 17px)',
        background: 'rgba(255,255,255,0.05)',
        border: '1px solid rgba(255,255,255,0.15)',
        borderRadius: '12px',
        color: '#ffffff',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        letterSpacing: '0.15em',
        fontWeight: '700',
        width: '100%',
        maxWidth: 'clamp(280px, 45vmin, 440px)', // Wider buttons
        textAlign: 'center',
        userSelect: 'none',
        display: 'block',
    },
    buttonPrimary: {
        background: '#ffffff',
        border: '1px solid #ffffff',
        color: '#000000',
        boxShadow: '0 4px 24px rgba(255, 255, 255, 0.15)',
        padding: 'clamp(16px, 2.5vh, 24px) clamp(36px, 6vw, 72px)',
        fontSize: 'clamp(16px, 2.5vmin, 20px)',
        fontWeight: '700',
        letterSpacing: '0.2em',
    },
    buttonSecondary: {
        background: 'rgba(255,255,255,0.04)',
        border: '1px solid rgba(255,255,255,0.12)',
        color: 'rgba(255,255,255,0.7)',
    },
    selector: {
        display: 'flex',
        alignItems: 'center',
        gap: '20px',
        marginBottom: '16px',
    },
    selectorBtn: {
        width: '36px',
        height: '36px',
        borderRadius: '50%',
        border: '1px solid rgba(255, 255, 255, 0.2)',
        background: 'transparent',
        color: '#ffffff',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
        fontSize: '1.1rem',
    },
    nValue: {
        fontSize: 'clamp(1.4rem, 3vmin, 2rem)',
        fontWeight: '600',
        color: '#ffffff',
        width: '48px',
        textAlign: 'center',
    },
    stats: {
        position: 'absolute',
        top: 'clamp(80px, 10vh, 120px)',
        left: '20px',
        fontSize: 'clamp(12px, 1.5vmin, 15px)',
        color: 'rgba(255, 255, 255, 0.6)',
        letterSpacing: '0.1em',
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        zIndex: 100
    },
    statValue: {
        color: '#ffffff',
        fontWeight: '700',
        fontSize: 'clamp(16px, 2.5vmin, 22px)',
    },
    tutorialOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        background: 'rgba(0, 0, 0, 0.95)',
        zIndex: 200,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'flex-start',
        backdropFilter: 'blur(10px)',
        overflowY: 'auto',
        padding: 'clamp(20px, 5vh, 40px) 20px',
    },
    tutorialStep: {
        width: 'clamp(60px, 10vmin, 90px)',
        height: 'clamp(60px, 10vmin, 90px)',
        borderRadius: '6px',
        border: '1px solid rgba(255, 255, 255, 0.1)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '24px',
        fontWeight: 'bold',
        color: '#fff',
        margin: '0 4px',
        transition: 'all 0.3s ease'
    },
    tutorialArrow: {
        position: 'absolute',
        height: '2px',
        background: '#ffffff',
        zIndex: 10
    }
};

return { STYLES };
